# Haskell Books available online
HASKELLBOOKSONLINE = RWH LYAH


#All Books available online
ALLBOOKS = HASKELLBOOKSONLINE

# Key for Google Docs
INDEXKEY = 0AtMdJdyllDEfdC1YMHE5NmNzNEc3bGx3aV9NbDc2V0E
